# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Installing packages...
    pip install gym[all]
    pip install numpy
    pip install matplotlib
    pip install tensorflow
    pip install keras
  displayName: 'Installing packages'

- script: python main.py
  timeoutInMinutes: 1440
  displayName: 'Running simulation...'